[features]
seeds = false
[programs.localnet]
solcrowdfunding = "B3kNNQCvmKywbcsHT6z6tNnTD49pijeCupBPKVvUm8rc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
